name 'reinsle-gerrit'
version '0.0.1'

author 'Robert Einsle <robert@einsle.de>'
license 'Apache20'
project_page 'http://github.com/reinsle/puppet-gerrit'
source ''
summary ''
description ''
dependency 'example42/puppi', '>=2.0.8'
